/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dynamo.lambda;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.lambda.runtime.Context;


public class Library {
    private DynamoDB dynamoDb;
    private String DYNAMODB_TABLE_NAME = "Taskmaster";
    private Regions REGION = Regions.US_WEST_2;

    public Task save(Task testTask, Context context) {
        testTask = new Task(testTask.getId(),testTask.getTitle(), testTask.getDescription(), testTask.getAssignee());


        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);


        ddbMapper.save(testTask);

        return testTask;
        }
    }
