package dynamo.lambda;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


import java.util.ArrayList;
@DynamoDBTable(tableName = "Taskmaster")
public class Task {

    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private String IMG;
    private ArrayList<UserHistory> userHistory;

    public Task() {}

    //  Tasks with UserHistories Constructor
    public Task(String id, String title, String description, String assignee) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.status = status;
        this.assignee = assignee;
        this.IMG = IMG;
        this.userHistory = new ArrayList<>();

    }

    //  Getters && Setters
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {return assignee;}

    public void setAssignee(String assignee) { this.assignee = assignee; }

    @DynamoDBAttribute
    public String getIMG() {
        return IMG;
    }

    public void setIMG(String IMG) {
        this.IMG = IMG;
    }


    @DynamoDBAttribute
    public ArrayList<UserHistory> getUserHistory() {
        return this.userHistory;
    }

    public void setUserHistory(ArrayList<UserHistory> userHistory) {
        this.userHistory = userHistory;
    }

    public void addUserHistory(UserHistory userHistory){
        this.userHistory.add(userHistory);
    }
}


